CREATE TABLE [dbo].[t_ClosedTrades] (
    [Buy]             BIT            NOT NULL,
    [Close]           FLOAT (53)     NULL,
    [CloseInPips]     FLOAT (53)     NULL,
    [GrossPL]         FLOAT (53)     NULL,
    [Id]              FLOAT (53)     NULL,
    [IsBuy]           BIT            NOT NULL,
    [IsParsed]        BIT            NOT NULL,
    [Limit]           FLOAT (53)     NULL,
    [LimitAmount]     FLOAT (53)     NULL,
    [LimitInPips]     FLOAT (53)     NULL,
    [Lots]            FLOAT (53)     NULL,
    [Open]            FLOAT (53)     NULL,
    [OpenInPips]      FLOAT (53)     NULL,
    [OpenOrderID]     NVARCHAR (255) NULL,
    [OpenOrderReqID]  NVARCHAR (255) NULL,
    [Pair]            NVARCHAR (255) NULL,
    [PipValue]        FLOAT (53)     NULL,
    [PL]              FLOAT (53)     NULL,
    [PointSize]       FLOAT (53)     NULL,
    [PointSizeFormat] NVARCHAR (255) NULL,
    [Remark]          NVARCHAR (255) NULL,
    [Stop]            FLOAT (53)     NULL,
    [StopAmount]      FLOAT (53)     NULL,
    [StopInPips]      FLOAT (53)     NULL,
    [Time]            DATETIME       NULL,
    [TimeClose]       DATETIME       NULL,
    [UnKnown]         NVARCHAR (255) NULL
);

