ALTER TABLE [dbo].[t_Price]
    ADD CONSTRAINT [PK_t_Price] PRIMARY KEY CLUSTERED ([ID] DESC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

