ALTER TABLE [dbo].[t_Offer]
    ADD CONSTRAINT [PK_t_Offer] PRIMARY KEY CLUSTERED ([Pair] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

