CREATE TABLE [dbo].[TradingMacro.bak] (
    [Pair]                             NVARCHAR (8)     NOT NULL,
    [TradingRatio]                     FLOAT (53)       NOT NULL,
    [UID]                              UNIQUEIDENTIFIER NOT NULL,
    [LimitBar]                         INT              NOT NULL,
    [CurrentLoss]                      FLOAT (53)       NOT NULL,
    [ReverseOnProfit]                  BIT              NOT NULL,
    [FreezLimit]                       INT              NOT NULL,
    [CorridorMethod]                   INT              NOT NULL,
    [FreezeStop]                       INT              NOT NULL,
    [FibMax]                           NVARCHAR (256)   NOT NULL,
    [FibMin]                           FLOAT (53)       NOT NULL,
    [CorridornessMin]                  FLOAT (53)       NOT NULL,
    [CorridorIterationsIn]             INT              NOT NULL,
    [CorridorIterationsOut]            INT              NOT NULL,
    [CorridorIterations]               NVARCHAR (16)    NOT NULL,
    [CorridorBarMinutes]               INT              NOT NULL,
    [PairIndex]                        INT              NOT NULL,
    [TradingGroup]                     INT              NOT NULL,
    [MaximumPositions]                 INT              NOT NULL,
    [IsActive]                         BIT              NOT NULL,
    [TradingMacroName]                 NVARCHAR (64)    NOT NULL,
    [LimitCorridorByBarHeight]         BIT              NOT NULL,
    [MaxLotByTakeProfitRatio]          FLOAT (53)       NOT NULL,
    [BarPeriodsLow]                    INT              NOT NULL,
    [BarPeriodsHigh]                   INT              NOT NULL,
    [StrictTradeClose]                 BIT              NOT NULL,
    [BarPeriodsLowHighRatio]           FLOAT (53)       NOT NULL,
    [LongMAPeriod]                     INT              NOT NULL,
    [CorridorAverageDaysBack]          INT              NOT NULL,
    [CorridorPeriodsStart]             INT              NOT NULL,
    [CorridorPeriodsLength]            INT              NOT NULL,
    [CorridorStartDate]                DATETIME         NULL,
    [CorridorRatioForRange]            FLOAT (53)       NOT NULL,
    [CorridorRatioForBreakout]         FLOAT (53)       NOT NULL,
    [RangeRatioForTradeLimit]          FLOAT (53)       NOT NULL,
    [TradeByAngle]                     BIT              NOT NULL,
    [ProfitToLossExitRatio]            FLOAT (53)       NOT NULL,
    [TradeByFirstWave]                 BIT              NULL,
    [PowerRowOffset]                   INT              NOT NULL,
    [RangeRatioForTradeStop]           FLOAT (53)       NOT NULL,
    [ReversePower]                     BIT              NOT NULL,
    [CorrelationTreshold]              FLOAT (53)       NOT NULL,
    [CloseOnProfitOnly]                BIT              NOT NULL,
    [CloseOnProfit]                    BIT              NOT NULL,
    [CloseOnOpen]                      BIT              NOT NULL,
    [StreachTradingDistance]           BIT              NOT NULL,
    [CloseAllOnProfit]                 BIT              NOT NULL,
    [ReverseStrategy]                  BIT              NOT NULL,
    [TradeAndAngleSynced]              BIT              NOT NULL,
    [TradingAngleRange]                FLOAT (53)       NOT NULL,
    [CloseByMomentum]                  BIT              NOT NULL,
    [TradeByRateDirection]             BIT              NOT NULL,
    [SupportDate]                      DATETIME         NULL,
    [ResistanceDate]                   DATETIME         NULL,
    [GannAnglesOffset]                 FLOAT (53)       NULL,
    [GannAngles]                       NVARCHAR (1024)  NOT NULL,
    [IsGannAnglesManual]               BIT              NOT NULL,
    [GannAnglesAnchorDate]             DATETIME         NULL,
    [SpreadShortToLongTreshold]        FLOAT (53)       NOT NULL,
    [SupportPriceStore]                FLOAT (53)       NULL,
    [ResistancePriceStore]             FLOAT (53)       NULL,
    [SuppResLevelsCount]               INT              NOT NULL,
    [DoStreatchRates]                  BIT              NOT NULL,
    [IsSuppResManual]                  BIT              NOT NULL,
    [TradeOnCrossOnly]                 BIT              NOT NULL,
    [TakeProfitFunctionInt]            INT              NOT NULL,
    [DoAdjustTimeframeByAllowedLot]    BIT              NOT NULL,
    [IsColdOnTrades]                   BIT              NOT NULL,
    [CorridorCrossesCountMinimum]      INT              NOT NULL,
    [StDevToSpreadRatio]               FLOAT (53)       NOT NULL,
    [LoadRatesSecondsWarning]          INT              NOT NULL,
    [CorridorHighLowMethodInt]         INT              NOT NULL,
    [CorridorStDevRatioMax]            FLOAT (53)       NOT NULL,
    [CorridorLengthMinimum]            FLOAT (53)       NOT NULL,
    [CorridorCrossHighLowMethodInt]    INT              NOT NULL,
    [MovingAverageTypeInt]             INT              NULL,
    [PriceCmaLevels]                   FLOAT (53)       NOT NULL,
    [VolumeTresholdIterations]         INT              NOT NULL,
    [StDevTresholdIterations]          INT              NOT NULL,
    [StDevAverageLeewayRatio]          FLOAT (53)       NOT NULL,
    [ExtreamCloseOffset]               INT              NOT NULL,
    [CurrentLossInPipsCloseAdjustment] FLOAT (53)       NOT NULL,
    [CorridorBigToSmallRatio]          FLOAT (53)       NOT NULL,
    [ResetOnBalance]                   FLOAT (53)       NULL,
    [VoltageFunction]                  INT              NOT NULL,
    [Timestamp]                        DATETIME         CONSTRAINT [DF_TradingMacro.bak_Timestamp] DEFAULT (getdate()) NOT NULL
);

