//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeHog.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_BarExtender
    {
        public int ID { get; set; }
        public int BarID { get; set; }
        public string Key { get; set; }
        public double Value { get; set; }
    
        public virtual t_Bar t_Bar { get; set; }
    }
}
