//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeHog.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Bar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_Bar()
        {
            this.t_BarExtender = new HashSet<t_BarExtender>();
        }
    
        public string Pair { get; set; }
        public int Period { get; set; }
        public System.DateTimeOffset StartDate { get; set; }
        public float AskHigh { get; set; }
        public float AskLow { get; set; }
        public float AskOpen { get; set; }
        public float AskClose { get; set; }
        public float BidHigh { get; set; }
        public float BidLow { get; set; }
        public float BidOpen { get; set; }
        public float BidClose { get; set; }
        public int Volume { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> StartDateLocal { get; set; }
        public int Row { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_BarExtender> t_BarExtender { get; set; }
    }
}
