//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeHog.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Trade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_Trade()
        {
            this.t_TradeValue = new HashSet<t_TradeValue>();
        }
    
        public string Id { get; set; }
        public bool Buy { get; set; }
        public double PL { get; set; }
        public double GrossPL { get; set; }
        public double Lot { get; set; }
        public string Pair { get; set; }
        public System.DateTime TimeOpen { get; set; }
        public System.DateTime TimeClose { get; set; }
        public string AccountId { get; set; }
        public double Commission { get; set; }
        public bool IsVirtual { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public double CorridorHeightInPips { get; set; }
        public double CorridorMinutesBack { get; set; }
        public System.Guid SessionId { get; set; }
        public double PriceOpen { get; set; }
        public double PriceClose { get; set; }
        public string SessionInfo { get; set; }
        public Nullable<double> RunningBalance { get; set; }
        public Nullable<double> RunningBalanceTotal { get; set; }
        public string SessionInfo2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_TradeValue> t_TradeValue { get; set; }
    }
}
