//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeHog.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_TradeValue
    {
        public int Id { get; set; }
        public string TradeId { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
    
        public virtual t_Trade t_Trade { get; set; }
    }
}
