//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeHog.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_BlackoutTime
    {
        public System.DateTimeOffset Time { get; set; }
        public string EventType { get; set; }
        public Nullable<System.DateTime> TimeLocal { get; set; }
        public Nullable<System.DateTimeOffset> TimeStart { get; set; }
        public System.DateTimeOffset TimeStop { get; set; }
        public Nullable<System.DateTime> TimeStartLocal { get; set; }
        public Nullable<System.DateTime> TimeStopLocal { get; set; }
    }
}
