//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Manheim.Model
{
    public partial class PreSale
    {
        #region Primitive Properties
    
        public virtual int PreSaleId
        {
            get;
            set;
        }
    
        public virtual int Ln
        {
            get;
            set;
        }
    
        public virtual string VIN
        {
            get { return _vIN; }
            set
            {
                if (_vIN != value)
                {
                    if (Vehicle != null && Vehicle.VIN != value)
                    {
                        Vehicle = null;
                    }
                    _vIN = value;
                }
            }
        }
        private string _vIN;
    
        public virtual System.DateTime SaleDate
        {
            get;
            set;
        }
    
        public virtual int AuctionId
        {
            get { return _auctionId; }
            set
            {
                if (_auctionId != value)
                {
                    if (Auction != null && Auction.AuctionId != value)
                    {
                        Auction = null;
                    }
                    _auctionId = value;
                }
            }
        }
        private int _auctionId;
    
        public virtual int Run
        {
            get;
            set;
        }
    
        public virtual int SellerId
        {
            get { return _sellerId; }
            set
            {
                if (_sellerId != value)
                {
                    if (Seller != null && Seller.SellerId != value)
                    {
                        Seller = null;
                    }
                    _sellerId = value;
                }
            }
        }
        private int _sellerId;

        #endregion
        #region Navigation Properties
    
        public virtual Auction Auction
        {
            get { return _auction; }
            set
            {
                if (!ReferenceEquals(_auction, value))
                {
                    var previousValue = _auction;
                    _auction = value;
                    FixupAuction(previousValue);
                }
            }
        }
        private Auction _auction;
    
        public virtual Vehicle Vehicle
        {
            get { return _vehicle; }
            set
            {
                if (!ReferenceEquals(_vehicle, value))
                {
                    var previousValue = _vehicle;
                    _vehicle = value;
                    FixupVehicle(previousValue);
                }
            }
        }
        private Vehicle _vehicle;
    
        public virtual Seller Seller
        {
            get { return _seller; }
            set
            {
                if (!ReferenceEquals(_seller, value))
                {
                    var previousValue = _seller;
                    _seller = value;
                    FixupSeller(previousValue);
                }
            }
        }
        private Seller _seller;

        #endregion
        #region Association Fixup
    
        private void FixupAuction(Auction previousValue)
        {
            if (previousValue != null && previousValue.PreSales.Contains(this))
            {
                previousValue.PreSales.Remove(this);
            }
    
            if (Auction != null)
            {
                if (!Auction.PreSales.Contains(this))
                {
                    Auction.PreSales.Add(this);
                }
                if (AuctionId != Auction.AuctionId)
                {
                    AuctionId = Auction.AuctionId;
                }
            }
        }
    
        private void FixupVehicle(Vehicle previousValue)
        {
            if (previousValue != null && previousValue.PreSales.Contains(this))
            {
                previousValue.PreSales.Remove(this);
            }
    
            if (Vehicle != null)
            {
                if (!Vehicle.PreSales.Contains(this))
                {
                    Vehicle.PreSales.Add(this);
                }
                if (VIN != Vehicle.VIN)
                {
                    VIN = Vehicle.VIN;
                }
            }
        }
    
        private void FixupSeller(Seller previousValue)
        {
            if (previousValue != null && previousValue.PreSales.Contains(this))
            {
                previousValue.PreSales.Remove(this);
            }
    
            if (Seller != null)
            {
                if (!Seller.PreSales.Contains(this))
                {
                    Seller.PreSales.Add(this);
                }
                if (SellerId != Seller.SellerId)
                {
                    SellerId = Seller.SellerId;
                }
            }
        }

        #endregion
    }
}
