

// ReSharper disable PossibleNullReferenceException
/*
This code was automatically generated by Daniel Vaughan's metadata generator.
Changes to this file may be lost if regeneration occurs.
http://danielvaughan.orpius.com
*/
using System.Windows;
using System;
using System.Linq;
using System.Linq.Expressions;


namespace HedgeHog.Alice.Server.XamlMetadata.Metadata
{
    /// <summary>Metadata for XAML App.xaml</summary>
    public static class AppXamlMetadata
    {
            /// <summary>Represents x:Key="Locator"/></summary>
            public static string LocatorKey { get { return "Locator"; } }


    }

}


namespace HedgeHog.Alice.Server.Metadata
{
    /// <summary>Metadata for class <see cref="HedgeHog.Alice.Server.App"/></summary>
    public static class AppMetadata
    {
                /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.App._CoreFX"/></summary>
        public const string _CoreFX = "_CoreFX";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.App.CoreFX"/></summary>
        public const string CoreFX = "CoreFX";

        /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.App._priceServiceHost"/></summary>
        public const string _priceServiceHost = "_priceServiceHost";

        /// <summary>Refers to method <see cref="HedgeHog.Alice.Server.App.App_DispatcherUnhandledException"/></summary>
        public const string App_DispatcherUnhandledException = "App_DispatcherUnhandledException";

        /// <summary>Refers to method <see cref="HedgeHog.Alice.Server.App.Application_Exit"/></summary>
        public const string Application_Exit = "Application_Exit";


        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.App.CoreFX"/></summary>
        public static PropertyPath CoreFXPath { get { return new PropertyPath("CoreFX"); } }

    }

    /// <summary>Metadata for class <see cref="HedgeHog.Alice.Server.PairInfo<TBar>"/></summary>
    public static class PairInfoMetadata
    {
                /// <summary>Refers to method <see cref="HedgeHog.Alice.Server.PairInfo{TBar}.RaiseReLoadRates"/></summary>
        public const string RaiseReLoadRates = "RaiseReLoadRates";

        /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.PairInfo{}._Rates"/></summary>
        public const string _Rates = "_Rates";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PairInfo{TBar}.Rates"/></summary>
        public const string Rates = "Rates";

        /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.PairInfo{}._BidHighToAskLowRatio"/></summary>
        public const string _BidHighToAskLowRatio = "_BidHighToAskLowRatio";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PairInfo{TBar}.BidHighToAskLowRatio"/></summary>
        public const string BidHighToAskLowRatio = "BidHighToAskLowRatio";

        /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.PairInfo{}._BidHighToAskLowRatioMA"/></summary>
        public const string _BidHighToAskLowRatioMA = "_BidHighToAskLowRatioMA";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PairInfo{TBar}.BidHighToAskLowRatioMA"/></summary>
        public const string BidHighToAskLowRatioMA = "BidHighToAskLowRatioMA";

        /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.PairInfo{}._StatsFramePeriods"/></summary>
        public const string _StatsFramePeriods = "_StatsFramePeriods";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PairInfo{TBar}.StatsFramePeriods"/></summary>
        public const string StatsFramePeriods = "StatsFramePeriods";

        /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.PairInfo{}._Period"/></summary>
        public const string _Period = "_Period";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PairInfo{TBar}.Period"/></summary>
        public const string Period = "Period";

        /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.PairInfo{}._Periods"/></summary>
        public const string _Periods = "_Periods";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PairInfo{TBar}.Periods"/></summary>
        public const string Periods = "Periods";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PairInfo{TBar}.Pair"/></summary>
        public const string Pair = "Pair";

        /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.PairInfo{}._LastDate"/></summary>
        public const string _LastDate = "_LastDate";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PairInfo{TBar}.LastDate"/></summary>
        public const string LastDate = "LastDate";

        /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.PairInfo{}._Count"/></summary>
        public const string _Count = "_Count";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PairInfo{TBar}.Count"/></summary>
        public const string Count = "Count";

        /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.PairInfo{}._PullsCount"/></summary>
        public const string _PullsCount = "_PullsCount";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PairInfo{TBar}.PullsCount"/></summary>
        public const string PullsCount = "PullsCount";

        /// <summary>Refers to method <see cref="HedgeHog.Alice.Server.PairInfo{TBar}.UpdateStatistics"/></summary>
        public const string UpdateStatistics = "UpdateStatistics";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PairInfo{TBar}.InPips"/></summary>
        public const string InPips = "InPips";


        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PairInfo{TBar}.Rates"/></summary>
        public static PropertyPath RatesPath { get { return new PropertyPath("Rates"); } }

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PairInfo{TBar}.BidHighToAskLowRatio"/></summary>
        public static PropertyPath BidHighToAskLowRatioPath { get { return new PropertyPath("BidHighToAskLowRatio"); } }

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PairInfo{TBar}.BidHighToAskLowRatioMA"/></summary>
        public static PropertyPath BidHighToAskLowRatioMAPath { get { return new PropertyPath("BidHighToAskLowRatioMA"); } }

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PairInfo{TBar}.StatsFramePeriods"/></summary>
        public static PropertyPath StatsFramePeriodsPath { get { return new PropertyPath("StatsFramePeriods"); } }

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PairInfo{TBar}.Period"/></summary>
        public static PropertyPath PeriodPath { get { return new PropertyPath("Period"); } }

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PairInfo{TBar}.Periods"/></summary>
        public static PropertyPath PeriodsPath { get { return new PropertyPath("Periods"); } }

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PairInfo{TBar}.Pair"/></summary>
        public static PropertyPath PairPath { get { return new PropertyPath("Pair"); } }

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PairInfo{TBar}.LastDate"/></summary>
        public static PropertyPath LastDatePath { get { return new PropertyPath("LastDate"); } }

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PairInfo{TBar}.Count"/></summary>
        public static PropertyPath CountPath { get { return new PropertyPath("Count"); } }

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PairInfo{TBar}.PullsCount"/></summary>
        public static PropertyPath PullsCountPath { get { return new PropertyPath("PullsCount"); } }

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PairInfo{TBar}.InPips"/></summary>
        public static PropertyPath InPipsPath { get { return new PropertyPath("InPips"); } }

    }

    /// <summary>Metadata for class <see cref="HedgeHog.Alice.Server.MainWindowModel"/></summary>
    public static class MainWindowModelMetadata
    {
                /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.MainWindowModel._Default"/></summary>
        public const string _Default = "_Default";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.MainWindowModel.Default"/></summary>
        public const string Default = "Default";

        /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.MainWindowModel._Period"/></summary>
        public const string _Period = "_Period";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.MainWindowModel.Period"/></summary>
        public const string Period = "Period";

        /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.MainWindowModel._Periods"/></summary>
        public const string _Periods = "_Periods";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.MainWindowModel.Periods"/></summary>
        public const string Periods = "Periods";

        /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.MainWindowModel._LogText"/></summary>
        public const string _LogText = "_LogText";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.MainWindowModel.LogText"/></summary>
        public const string LogText = "LogText";

        /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.MainWindowModel._logQueue"/></summary>
        public const string _logQueue = "_logQueue";

        /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.MainWindowModel._log"/></summary>
        public const string _log = "_log";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.MainWindowModel.Log"/></summary>
        public const string Log = "Log";

        /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.MainWindowModel._mSink"/></summary>
        public const string _mSink = "_mSink";

        /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.MainWindowModel._IsLoggedIn"/></summary>
        public const string _IsLoggedIn = "_IsLoggedIn";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.MainWindowModel.IsLoggedIn"/></summary>
        public const string IsLoggedIn = "IsLoggedIn";

        /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.MainWindowModel._Title"/></summary>
        public const string _Title = "_Title";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.MainWindowModel.Title"/></summary>
        public const string Title = "Title";

        /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.MainWindowModel._coreFX"/></summary>
        public const string _coreFX = "_coreFX";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.MainWindowModel.coreFX"/></summary>
        public const string coreFX = "coreFX";

        /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.MainWindowModel._PairInfos"/></summary>
        public const string _PairInfos = "_PairInfos";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.MainWindowModel.PairInfos"/></summary>
        public const string PairInfos = "PairInfos";

        /// <summary>Refers to method <see cref="HedgeHog.Alice.Server.MainWindowModel.coreFX_LoggedOffEvent"/></summary>
        public const string coreFX_LoggedOffEvent = "coreFX_LoggedOffEvent";

        /// <summary>Refers to method <see cref="HedgeHog.Alice.Server.MainWindowModel.coreFX_LoggedInEvent"/></summary>
        public const string coreFX_LoggedInEvent = "coreFX_LoggedInEvent";

        /// <summary>Refers to method <see cref="HedgeHog.Alice.Server.MainWindowModel.mSink_ITradeDeskEvents_Event_OnSessionStatusChanged"/></summary>
        public const string mSink_ITradeDeskEvents_Event_OnSessionStatusChanged = "mSink_ITradeDeskEvents_Event_OnSessionStatusChanged";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.MainWindowModel.Account"/></summary>
        public const string Account = "Account";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.MainWindowModel.Password"/></summary>
        public const string Password = "Password";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.MainWindowModel.IsDemo"/></summary>
        public const string IsDemo = "IsDemo";

        /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.MainWindowModel.aaaa"/></summary>
        public const string aaaa = "aaaa";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.MainWindowModel.AAAA"/></summary>
        public const string AAAA = "AAAA";

        /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.MainWindowModel._LoginCommand"/></summary>
        public const string _LoginCommand = "_LoginCommand";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.MainWindowModel.LoginCommand"/></summary>
        public const string LoginCommand = "LoginCommand";

        /// <summary>Refers to method <see cref="HedgeHog.Alice.Server.MainWindowModel.Login"/></summary>
        public const string Login = "Login";


        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.MainWindowModel.Default"/></summary>
        public static PropertyPath DefaultPath { get { return new PropertyPath("Default"); } }

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.MainWindowModel.Period"/></summary>
        public static PropertyPath PeriodPath { get { return new PropertyPath("Period"); } }

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.MainWindowModel.Periods"/></summary>
        public static PropertyPath PeriodsPath { get { return new PropertyPath("Periods"); } }

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.MainWindowModel.LogText"/></summary>
        public static PropertyPath LogTextPath { get { return new PropertyPath("LogText"); } }

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.MainWindowModel.Log"/></summary>
        public static PropertyPath LogPath { get { return new PropertyPath("Log"); } }

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.MainWindowModel.IsLoggedIn"/></summary>
        public static PropertyPath IsLoggedInPath { get { return new PropertyPath("IsLoggedIn"); } }

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.MainWindowModel.Title"/></summary>
        public static PropertyPath TitlePath { get { return new PropertyPath("Title"); } }

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.MainWindowModel.coreFX"/></summary>
        public static PropertyPath coreFXPath { get { return new PropertyPath("coreFX"); } }

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.MainWindowModel.PairInfos"/></summary>
        public static PropertyPath PairInfosPath { get { return new PropertyPath("PairInfos"); } }

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.MainWindowModel.Account"/></summary>
        public static PropertyPath AccountPath { get { return new PropertyPath("Account"); } }

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.MainWindowModel.Password"/></summary>
        public static PropertyPath PasswordPath { get { return new PropertyPath("Password"); } }

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.MainWindowModel.IsDemo"/></summary>
        public static PropertyPath IsDemoPath { get { return new PropertyPath("IsDemo"); } }

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.MainWindowModel.AAAA"/></summary>
        public static PropertyPath AAAAPath { get { return new PropertyPath("AAAA"); } }

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.MainWindowModel.LoginCommand"/></summary>
        public static PropertyPath LoginCommandPath { get { return new PropertyPath("LoginCommand"); } }

    }

    /// <summary>Metadata for class <see cref="HedgeHog.Alice.Server.MainWindow"/></summary>
    public static class MainWindowMetadata
    {
                /// <summary>Refers to method <see cref="HedgeHog.Alice.Server.MainWindow.MainWindow_Closed"/></summary>
        public const string MainWindow_Closed = "MainWindow_Closed";


    }

    /// <summary>Metadata for interface <see cref="HedgeHog.Alice.Server.IPriceService"/></summary>
    public static class IPriceServiceMetadata
    {
                /// <summary>Refers to method <see cref="HedgeHog.Alice.Server.IPriceService.FillPrice"/></summary>
        public const string FillPrice = "FillPrice";

        /// <summary>Refers to method <see cref="HedgeHog.Alice.Server.IPriceService.PriceStatistics"/></summary>
        public const string PriceStatistics = "PriceStatistics";


    }

    /// <summary>Metadata for class <see cref="HedgeHog.Alice.Server.PriceService"/></summary>
    public static class PriceServiceMetadata
    {
                /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.PriceService._fw"/></summary>
        public const string _fw = "_fw";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PriceService.Log"/></summary>
        public const string Log = "Log";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PriceService.PairInfos"/></summary>
        public const string PairInfos = "PairInfos";

        /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.PriceService.THROTTLE_INTERVAL"/></summary>
        public const string THROTTLE_INTERVAL = "THROTTLE_INTERVAL";

        /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.PriceService._LoadRatesSubjectLocker"/></summary>
        public const string _LoadRatesSubjectLocker = "_LoadRatesSubjectLocker";

        /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.PriceService._LoadRatesSubject"/></summary>
        public const string _LoadRatesSubject = "_LoadRatesSubject";

        /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.PriceService._priceChangedSubscribsion"/></summary>
        public const string _priceChangedSubscribsion = "_priceChangedSubscribsion";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PriceService.LoadRatesSubject"/></summary>
        public const string LoadRatesSubject = "LoadRatesSubject";

        /// <summary>Refers to method <see cref="HedgeHog.Alice.Server.PriceService.OnLoadRates"/></summary>
        public const string OnLoadRates = "OnLoadRates";

        /// <summary>Refers to method <see cref="HedgeHog.Alice.Server.PriceService.LoadRates"/></summary>
        public const string LoadRates = "LoadRates";

        /// <summary>Refers to method <see cref="HedgeHog.Alice.Server.PriceService.MainWindowModel_PropertyChanged"/></summary>
        public const string MainWindowModel_PropertyChanged = "MainWindowModel_PropertyChanged";

        /// <summary>Refers to method <see cref="HedgeHog.Alice.Server.PriceService.RriceInfo_ReLoadRates"/></summary>
        public const string RriceInfo_ReLoadRates = "RriceInfo_ReLoadRates";

        /// <summary>Refers to method <see cref="HedgeHog.Alice.Server.PriceService.AfterPairLoaded"/></summary>
        public const string AfterPairLoaded = "AfterPairLoaded";

        /// <summary>Refers to method <see cref="HedgeHog.Alice.Server.PriceService.CoreFX_LoggedInEvent"/></summary>
        public const string CoreFX_LoggedInEvent = "CoreFX_LoggedInEvent";

        /// <summary>Refers to method <see cref="HedgeHog.Alice.Server.PriceService.fw_PriceChanged"/></summary>
        public const string fw_PriceChanged = "fw_PriceChanged";

        /// <summary>Refers to method <see cref="HedgeHog.Alice.Server.PriceService.GetOrAddPairInfo"/></summary>
        public const string GetOrAddPairInfo = "GetOrAddPairInfo";

        /// <summary>Refers to method <see cref="HedgeHog.Alice.Server.PriceService.AddOfferPair"/></summary>
        public const string AddOfferPair = "AddOfferPair";

        /// <summary>Refers to method <see cref="HedgeHog.Alice.Server.PriceService.FillPrice"/></summary>
        public const string FillPrice = "FillPrice";

        /// <summary>Refers to method <see cref="HedgeHog.Alice.Server.PriceService.PriceStatistics"/></summary>
        public const string PriceStatistics = "PriceStatistics";


        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PriceService.Log"/></summary>
        public static PropertyPath LogPath { get { return new PropertyPath("Log"); } }

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PriceService.PairInfos"/></summary>
        public static PropertyPath PairInfosPath { get { return new PropertyPath("PairInfos"); } }

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PriceService.LoadRatesSubject"/></summary>
        public static PropertyPath LoadRatesSubjectPath { get { return new PropertyPath("LoadRatesSubject"); } }

    }

    /// <summary>Metadata for class <see cref="HedgeHog.Alice.Server.PriceStatistics"/></summary>
    public static class PriceStatisticsMetadata
    {
                /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PriceStatistics.BidHighAskLowSpread"/></summary>
        public const string BidHighAskLowSpread = "BidHighAskLowSpread";


        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.PriceStatistics.BidHighAskLowSpread"/></summary>
        public static PropertyPath BidHighAskLowSpreadPath { get { return new PropertyPath("BidHighAskLowSpread"); } }

    }

}

namespace HedgeHog.Alice.Server.Properties.Metadata
{
    /// <summary>Metadata for class <see cref="HedgeHog.Alice.Server.Properties.Resources"/></summary>
    public static class ResourcesMetadata
    {
                /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.Properties.Resources.resourceMan"/></summary>
        public const string resourceMan = "resourceMan";

        /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.Properties.Resources.resourceCulture"/></summary>
        public const string resourceCulture = "resourceCulture";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.Properties.Resources.ResourceManager"/></summary>
        public const string ResourceManager = "ResourceManager";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.Properties.Resources.Culture"/></summary>
        public const string Culture = "Culture";


        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.Properties.Resources.ResourceManager"/></summary>
        public static PropertyPath ResourceManagerPath { get { return new PropertyPath("ResourceManager"); } }

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.Properties.Resources.Culture"/></summary>
        public static PropertyPath CulturePath { get { return new PropertyPath("Culture"); } }

    }

    /// <summary>Metadata for class <see cref="HedgeHog.Alice.Server.Properties.Settings"/></summary>
    public static class SettingsMetadata
    {
                /// <summary>Refers to field <see cref="HedgeHog.Alice.Server.Properties.Settings.defaultInstance"/></summary>
        public const string defaultInstance = "defaultInstance";

        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.Properties.Settings.Default"/></summary>
        public const string Default = "Default";


        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.Properties.Settings.Default"/></summary>
        public static PropertyPath DefaultPath { get { return new PropertyPath("Default"); } }

    }

}

namespace HedgeHog.Alice.Server.ViewModel.Metadata
{
    /// <summary>Metadata for class <see cref="HedgeHog.Alice.Server.ViewModel.MainViewModel"/></summary>
    public static class MainViewModelMetadata
    {
        
    }

    /// <summary>Metadata for class <see cref="HedgeHog.Alice.Server.ViewModel.ViewModelLocator"/></summary>
    public static class ViewModelLocatorMetadata
    {
                /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.ViewModel.ViewModelLocator.Main"/></summary>
        public const string Main = "Main";

        /// <summary>Refers to method <see cref="HedgeHog.Alice.Server.ViewModel.ViewModelLocator.Cleanup"/></summary>
        public const string Cleanup = "Cleanup";


        /// <summary>Refers to property <see cref="HedgeHog.Alice.Server.ViewModel.ViewModelLocator.Main"/></summary>
        public static PropertyPath MainPath { get { return new PropertyPath("Main"); } }

    }

}

// ReSharper restore PossibleNullReferenceException
