CREATE PROCEDURE sRunWorkShift AS


SELECT TOP 1 PP1.Start,ISNULL(PP2.Stop,PP1.Stop) Stop
INTO #Out
FROM PunchPair PP1
LEFT OUTER JOIN PunchPair PP2 ON DATEDIFF(n,PP1.Stop,PP2.Start) BETWEEN 1 AND 60
WHERE PP1.Start > (SELECT ISNULL(MAX(Stop),'1/1/1900') FROM WorkShift)

INSERT INTO WorkShift
SELECT * 
FROM #Out