CREATE TABLE [dbo].[t_ClosedTrades] (
    [Buy]             BIT            NOT NULL,
    [Close]           FLOAT          NULL,
    [CloseInPips]     FLOAT          NULL,
    [GrossPL]         FLOAT          NULL,
    [Id]              FLOAT          NULL,
    [IsBuy]           BIT            NOT NULL,
    [IsParsed]        BIT            NOT NULL,
    [Limit]           FLOAT          NULL,
    [LimitAmount]     FLOAT          NULL,
    [LimitInPips]     FLOAT          NULL,
    [Lots]            FLOAT          NULL,
    [Open]            FLOAT          NULL,
    [OpenInPips]      FLOAT          NULL,
    [OpenOrderID]     NVARCHAR (255) NULL,
    [OpenOrderReqID]  NVARCHAR (255) NULL,
    [Pair]            NVARCHAR (255) NULL,
    [PipValue]        FLOAT          NULL,
    [PL]              FLOAT          NULL,
    [PointSize]       FLOAT          NULL,
    [PointSizeFormat] NVARCHAR (255) NULL,
    [Remark]          NVARCHAR (255) NULL,
    [Stop]            FLOAT          NULL,
    [StopAmount]      FLOAT          NULL,
    [StopInPips]      FLOAT          NULL,
    [Time]            DATETIME       NULL,
    [TimeClose]       DATETIME       NULL,
    [UnKnown]         NVARCHAR (255) NULL
);

