ALTER TABLE [dbo].[t_Volts]
    ADD CONSTRAINT [PK_t_Volts] PRIMARY KEY CLUSTERED ([StartDate] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

