//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manheim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auction
    {
        public Auction()
        {
            this.PreSales = new HashSet<PreSale>();
        }
    
        public int AuctionId { get; set; }
        public string Name { get; set; }
        public int PreSaleManagerId { get; set; }
        public string StateCode { get; set; }
    
        public virtual Manager PreSaleManager { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<PreSale> PreSales { get; set; }
    }
}
