//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ManheimModel", "FK_Auction_Manager", "Manager", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Manheim.Model.Manager), "Auction", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Manheim.Model.Auction), true)]
[assembly: EdmRelationshipAttribute("ManheimModel", "FK_Auction_State", "State", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Manheim.Model.State), "Auction", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Manheim.Model.Auction), true)]
[assembly: EdmRelationshipAttribute("ManheimModel", "FK_PreSale_Auction", "Auction", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Manheim.Model.Auction), "PreSale", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Manheim.Model.PreSale), true)]
[assembly: EdmRelationshipAttribute("ManheimModel", "FK_PreSale_Vehicle", "Vehicle", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Manheim.Model.Vehicle), "PreSale", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Manheim.Model.PreSale), true)]
[assembly: EdmRelationshipAttribute("ManheimModel", "FK_Vehicle_VehicleStatus", "VehicleStatu", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Manheim.Model.VehicleStatus), "Vehicle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Manheim.Model.Vehicle), true)]
[assembly: EdmRelationshipAttribute("ManheimModel", "FK_PreSale_Seller", "Seller", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Manheim.Model.Seller), "PreSale", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Manheim.Model.PreSale), true)]

#endregion

namespace Manheim.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ManheimEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ManheimEntities object using the connection string found in the 'ManheimEntities' section of the application configuration file.
        /// </summary>
        public ManheimEntities() : base("name=ManheimEntities", "ManheimEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ManheimEntities object.
        /// </summary>
        public ManheimEntities(string connectionString) : base(connectionString, "ManheimEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ManheimEntities object.
        /// </summary>
        public ManheimEntities(EntityConnection connection) : base(connection, "ManheimEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Auction> Auctions
        {
            get
            {
                if ((_Auctions == null))
                {
                    _Auctions = base.CreateObjectSet<Auction>("Auctions");
                }
                return _Auctions;
            }
        }
        private ObjectSet<Auction> _Auctions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Manager> Managers
        {
            get
            {
                if ((_Managers == null))
                {
                    _Managers = base.CreateObjectSet<Manager>("Managers");
                }
                return _Managers;
            }
        }
        private ObjectSet<Manager> _Managers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<State> States
        {
            get
            {
                if ((_States == null))
                {
                    _States = base.CreateObjectSet<State>("States");
                }
                return _States;
            }
        }
        private ObjectSet<State> _States;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PreSale> PreSales
        {
            get
            {
                if ((_PreSales == null))
                {
                    _PreSales = base.CreateObjectSet<PreSale>("PreSales");
                }
                return _PreSales;
            }
        }
        private ObjectSet<PreSale> _PreSales;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Vehicle> Vehicles
        {
            get
            {
                if ((_Vehicles == null))
                {
                    _Vehicles = base.CreateObjectSet<Vehicle>("Vehicles");
                }
                return _Vehicles;
            }
        }
        private ObjectSet<Vehicle> _Vehicles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VehicleStatus> VehicleStatuses
        {
            get
            {
                if ((_VehicleStatuses == null))
                {
                    _VehicleStatuses = base.CreateObjectSet<VehicleStatus>("VehicleStatuses");
                }
                return _VehicleStatuses;
            }
        }
        private ObjectSet<VehicleStatus> _VehicleStatuses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Seller> Sellers
        {
            get
            {
                if ((_Sellers == null))
                {
                    _Sellers = base.CreateObjectSet<Seller>("Sellers");
                }
                return _Sellers;
            }
        }
        private ObjectSet<Seller> _Sellers;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Auctions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAuctions(Auction auction)
        {
            base.AddObject("Auctions", auction);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Managers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToManagers(Manager manager)
        {
            base.AddObject("Managers", manager);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the States EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStates(State state)
        {
            base.AddObject("States", state);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PreSales EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPreSales(PreSale preSale)
        {
            base.AddObject("PreSales", preSale);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Vehicles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVehicles(Vehicle vehicle)
        {
            base.AddObject("Vehicles", vehicle);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VehicleStatuses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVehicleStatuses(VehicleStatus vehicleStatus)
        {
            base.AddObject("VehicleStatuses", vehicleStatus);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sellers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSellers(Seller seller)
        {
            base.AddObject("Sellers", seller);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ManheimModel", Name="Auction")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Auction : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Auction object.
        /// </summary>
        /// <param name="auctionId">Initial value of the AuctionId property.</param>
        /// <param name="preSaleManagerId">Initial value of the PreSaleManagerId property.</param>
        /// <param name="stateCode">Initial value of the StateCode property.</param>
        public static Auction CreateAuction(global::System.Int32 auctionId, global::System.Int32 preSaleManagerId, global::System.String stateCode)
        {
            Auction auction = new Auction();
            auction.AuctionId = auctionId;
            auction.PreSaleManagerId = preSaleManagerId;
            auction.StateCode = stateCode;
            return auction;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AuctionId
        {
            get
            {
                return _AuctionId;
            }
            set
            {
                if (_AuctionId != value)
                {
                    OnAuctionIdChanging(value);
                    ReportPropertyChanging("AuctionId");
                    _AuctionId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AuctionId");
                    OnAuctionIdChanged();
                }
            }
        }
        private global::System.Int32 _AuctionId;
        partial void OnAuctionIdChanging(global::System.Int32 value);
        partial void OnAuctionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PreSaleManagerId
        {
            get
            {
                return _PreSaleManagerId;
            }
            set
            {
                OnPreSaleManagerIdChanging(value);
                ReportPropertyChanging("PreSaleManagerId");
                _PreSaleManagerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PreSaleManagerId");
                OnPreSaleManagerIdChanged();
            }
        }
        private global::System.Int32 _PreSaleManagerId;
        partial void OnPreSaleManagerIdChanging(global::System.Int32 value);
        partial void OnPreSaleManagerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StateCode
        {
            get
            {
                return _StateCode;
            }
            set
            {
                OnStateCodeChanging(value);
                ReportPropertyChanging("StateCode");
                _StateCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StateCode");
                OnStateCodeChanged();
            }
        }
        private global::System.String _StateCode;
        partial void OnStateCodeChanging(global::System.String value);
        partial void OnStateCodeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ManheimModel", "FK_Auction_Manager", "Manager")]
        public Manager PreSaleManager
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Manager>("ManheimModel.FK_Auction_Manager", "Manager").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Manager>("ManheimModel.FK_Auction_Manager", "Manager").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Manager> PreSaleManagerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Manager>("ManheimModel.FK_Auction_Manager", "Manager");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Manager>("ManheimModel.FK_Auction_Manager", "Manager", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ManheimModel", "FK_Auction_State", "State")]
        public State State
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<State>("ManheimModel.FK_Auction_State", "State").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<State>("ManheimModel.FK_Auction_State", "State").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<State> StateReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<State>("ManheimModel.FK_Auction_State", "State");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<State>("ManheimModel.FK_Auction_State", "State", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ManheimModel", "FK_PreSale_Auction", "PreSale")]
        public EntityCollection<PreSale> PreSales
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PreSale>("ManheimModel.FK_PreSale_Auction", "PreSale");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PreSale>("ManheimModel.FK_PreSale_Auction", "PreSale", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ManheimModel", Name="Manager")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Manager : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Manager object.
        /// </summary>
        /// <param name="managerId">Initial value of the ManagerId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="phone">Initial value of the Phone property.</param>
        /// <param name="fax">Initial value of the Fax property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        public static Manager CreateManager(global::System.Int32 managerId, global::System.String name, global::System.String title, global::System.String phone, global::System.String fax, global::System.String email)
        {
            Manager manager = new Manager();
            manager.ManagerId = managerId;
            manager.Name = name;
            manager.Title = title;
            manager.Phone = phone;
            manager.Fax = fax;
            manager.Email = email;
            return manager;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ManagerId
        {
            get
            {
                return _ManagerId;
            }
            set
            {
                if (_ManagerId != value)
                {
                    OnManagerIdChanging(value);
                    ReportPropertyChanging("ManagerId");
                    _ManagerId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ManagerId");
                    OnManagerIdChanged();
                }
            }
        }
        private global::System.Int32 _ManagerId;
        partial void OnManagerIdChanging(global::System.Int32 value);
        partial void OnManagerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Fax
        {
            get
            {
                return _Fax;
            }
            set
            {
                OnFaxChanging(value);
                ReportPropertyChanging("Fax");
                _Fax = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Fax");
                OnFaxChanged();
            }
        }
        private global::System.String _Fax;
        partial void OnFaxChanging(global::System.String value);
        partial void OnFaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ManheimModel", Name="PreSale")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PreSale : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PreSale object.
        /// </summary>
        /// <param name="preSaleId">Initial value of the PreSaleId property.</param>
        /// <param name="ln">Initial value of the Ln property.</param>
        /// <param name="vIN">Initial value of the VIN property.</param>
        /// <param name="saleDate">Initial value of the SaleDate property.</param>
        /// <param name="auctionId">Initial value of the AuctionId property.</param>
        /// <param name="run">Initial value of the Run property.</param>
        /// <param name="sellerId">Initial value of the SellerId property.</param>
        public static PreSale CreatePreSale(global::System.Int32 preSaleId, global::System.Int32 ln, global::System.String vIN, global::System.DateTime saleDate, global::System.Int32 auctionId, global::System.Int32 run, global::System.Int32 sellerId)
        {
            PreSale preSale = new PreSale();
            preSale.PreSaleId = preSaleId;
            preSale.Ln = ln;
            preSale.VIN = vIN;
            preSale.SaleDate = saleDate;
            preSale.AuctionId = auctionId;
            preSale.Run = run;
            preSale.SellerId = sellerId;
            return preSale;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PreSaleId
        {
            get
            {
                return _PreSaleId;
            }
            set
            {
                if (_PreSaleId != value)
                {
                    OnPreSaleIdChanging(value);
                    ReportPropertyChanging("PreSaleId");
                    _PreSaleId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PreSaleId");
                    OnPreSaleIdChanged();
                }
            }
        }
        private global::System.Int32 _PreSaleId;
        partial void OnPreSaleIdChanging(global::System.Int32 value);
        partial void OnPreSaleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Ln
        {
            get
            {
                return _Ln;
            }
            set
            {
                OnLnChanging(value);
                ReportPropertyChanging("Ln");
                _Ln = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ln");
                OnLnChanged();
            }
        }
        private global::System.Int32 _Ln;
        partial void OnLnChanging(global::System.Int32 value);
        partial void OnLnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String VIN
        {
            get
            {
                return _VIN;
            }
            set
            {
                OnVINChanging(value);
                ReportPropertyChanging("VIN");
                _VIN = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("VIN");
                OnVINChanged();
            }
        }
        private global::System.String _VIN;
        partial void OnVINChanging(global::System.String value);
        partial void OnVINChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SaleDate
        {
            get
            {
                return _SaleDate;
            }
            set
            {
                OnSaleDateChanging(value);
                ReportPropertyChanging("SaleDate");
                _SaleDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SaleDate");
                OnSaleDateChanged();
            }
        }
        private global::System.DateTime _SaleDate;
        partial void OnSaleDateChanging(global::System.DateTime value);
        partial void OnSaleDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AuctionId
        {
            get
            {
                return _AuctionId;
            }
            set
            {
                OnAuctionIdChanging(value);
                ReportPropertyChanging("AuctionId");
                _AuctionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AuctionId");
                OnAuctionIdChanged();
            }
        }
        private global::System.Int32 _AuctionId;
        partial void OnAuctionIdChanging(global::System.Int32 value);
        partial void OnAuctionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Run
        {
            get
            {
                return _Run;
            }
            set
            {
                OnRunChanging(value);
                ReportPropertyChanging("Run");
                _Run = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Run");
                OnRunChanged();
            }
        }
        private global::System.Int32 _Run;
        partial void OnRunChanging(global::System.Int32 value);
        partial void OnRunChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SellerId
        {
            get
            {
                return _SellerId;
            }
            set
            {
                OnSellerIdChanging(value);
                ReportPropertyChanging("SellerId");
                _SellerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SellerId");
                OnSellerIdChanged();
            }
        }
        private global::System.Int32 _SellerId;
        partial void OnSellerIdChanging(global::System.Int32 value);
        partial void OnSellerIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ManheimModel", "FK_PreSale_Auction", "Auction")]
        public Auction Auction
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Auction>("ManheimModel.FK_PreSale_Auction", "Auction").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Auction>("ManheimModel.FK_PreSale_Auction", "Auction").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Auction> AuctionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Auction>("ManheimModel.FK_PreSale_Auction", "Auction");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Auction>("ManheimModel.FK_PreSale_Auction", "Auction", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ManheimModel", "FK_PreSale_Vehicle", "Vehicle")]
        public Vehicle Vehicle
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vehicle>("ManheimModel.FK_PreSale_Vehicle", "Vehicle").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vehicle>("ManheimModel.FK_PreSale_Vehicle", "Vehicle").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Vehicle> VehicleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vehicle>("ManheimModel.FK_PreSale_Vehicle", "Vehicle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Vehicle>("ManheimModel.FK_PreSale_Vehicle", "Vehicle", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ManheimModel", "FK_PreSale_Seller", "Seller")]
        public Seller Seller
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Seller>("ManheimModel.FK_PreSale_Seller", "Seller").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Seller>("ManheimModel.FK_PreSale_Seller", "Seller").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Seller> SellerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Seller>("ManheimModel.FK_PreSale_Seller", "Seller");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Seller>("ManheimModel.FK_PreSale_Seller", "Seller", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ManheimModel", Name="Seller")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Seller : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Seller object.
        /// </summary>
        /// <param name="sellerId">Initial value of the SellerId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Seller CreateSeller(global::System.Int32 sellerId, global::System.String name)
        {
            Seller seller = new Seller();
            seller.SellerId = sellerId;
            seller.Name = name;
            return seller;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SellerId
        {
            get
            {
                return _SellerId;
            }
            set
            {
                if (_SellerId != value)
                {
                    OnSellerIdChanging(value);
                    ReportPropertyChanging("SellerId");
                    _SellerId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SellerId");
                    OnSellerIdChanged();
                }
            }
        }
        private global::System.Int32 _SellerId;
        partial void OnSellerIdChanging(global::System.Int32 value);
        partial void OnSellerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ManheimModel", "FK_PreSale_Seller", "PreSale")]
        public EntityCollection<PreSale> PreSales
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PreSale>("ManheimModel.FK_PreSale_Seller", "PreSale");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PreSale>("ManheimModel.FK_PreSale_Seller", "PreSale", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ManheimModel", Name="State")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class State : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new State object.
        /// </summary>
        /// <param name="stateCode">Initial value of the StateCode property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static State CreateState(global::System.String stateCode, global::System.String name)
        {
            State state = new State();
            state.StateCode = stateCode;
            state.Name = name;
            return state;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StateCode
        {
            get
            {
                return _StateCode;
            }
            set
            {
                if (_StateCode != value)
                {
                    OnStateCodeChanging(value);
                    ReportPropertyChanging("StateCode");
                    _StateCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("StateCode");
                    OnStateCodeChanged();
                }
            }
        }
        private global::System.String _StateCode;
        partial void OnStateCodeChanging(global::System.String value);
        partial void OnStateCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ManheimModel", Name="Vehicle")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Vehicle : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Vehicle object.
        /// </summary>
        /// <param name="vIN">Initial value of the VIN property.</param>
        /// <param name="year">Initial value of the Year property.</param>
        /// <param name="make">Initial value of the Make property.</param>
        /// <param name="model">Initial value of the Model property.</param>
        /// <param name="salvage">Initial value of the Salvage property.</param>
        /// <param name="statusId">Initial value of the StatusId property.</param>
        public static Vehicle CreateVehicle(global::System.String vIN, global::System.Int32 year, global::System.String make, global::System.String model, global::System.Boolean salvage, global::System.Int32 statusId)
        {
            Vehicle vehicle = new Vehicle();
            vehicle.VIN = vIN;
            vehicle.Year = year;
            vehicle.Make = make;
            vehicle.Model = model;
            vehicle.Salvage = salvage;
            vehicle.StatusId = statusId;
            return vehicle;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String VIN
        {
            get
            {
                return _VIN;
            }
            set
            {
                if (_VIN != value)
                {
                    OnVINChanging(value);
                    ReportPropertyChanging("VIN");
                    _VIN = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("VIN");
                    OnVINChanged();
                }
            }
        }
        private global::System.String _VIN;
        partial void OnVINChanging(global::System.String value);
        partial void OnVINChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Year
        {
            get
            {
                return _Year;
            }
            set
            {
                OnYearChanging(value);
                ReportPropertyChanging("Year");
                _Year = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Year");
                OnYearChanged();
            }
        }
        private global::System.Int32 _Year;
        partial void OnYearChanging(global::System.Int32 value);
        partial void OnYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Make
        {
            get
            {
                return _Make;
            }
            set
            {
                OnMakeChanging(value);
                ReportPropertyChanging("Make");
                _Make = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Make");
                OnMakeChanged();
            }
        }
        private global::System.String _Make;
        partial void OnMakeChanging(global::System.String value);
        partial void OnMakeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Model
        {
            get
            {
                return _Model;
            }
            set
            {
                OnModelChanging(value);
                ReportPropertyChanging("Model");
                _Model = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Model");
                OnModelChanged();
            }
        }
        private global::System.String _Model;
        partial void OnModelChanging(global::System.String value);
        partial void OnModelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BodyStyle
        {
            get
            {
                return _BodyStyle;
            }
            set
            {
                OnBodyStyleChanging(value);
                ReportPropertyChanging("BodyStyle");
                _BodyStyle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BodyStyle");
                OnBodyStyleChanged();
            }
        }
        private global::System.String _BodyStyle;
        partial void OnBodyStyleChanging(global::System.String value);
        partial void OnBodyStyleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TrimLevel
        {
            get
            {
                return _TrimLevel;
            }
            set
            {
                OnTrimLevelChanging(value);
                ReportPropertyChanging("TrimLevel");
                _TrimLevel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TrimLevel");
                OnTrimLevelChanged();
            }
        }
        private global::System.String _TrimLevel;
        partial void OnTrimLevelChanging(global::System.String value);
        partial void OnTrimLevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VehicleType
        {
            get
            {
                return _VehicleType;
            }
            set
            {
                OnVehicleTypeChanging(value);
                ReportPropertyChanging("VehicleType");
                _VehicleType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VehicleType");
                OnVehicleTypeChanged();
            }
        }
        private global::System.String _VehicleType;
        partial void OnVehicleTypeChanging(global::System.String value);
        partial void OnVehicleTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Doors
        {
            get
            {
                return _Doors;
            }
            set
            {
                OnDoorsChanging(value);
                ReportPropertyChanging("Doors");
                _Doors = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Doors");
                OnDoorsChanged();
            }
        }
        private Nullable<global::System.Int32> _Doors;
        partial void OnDoorsChanging(Nullable<global::System.Int32> value);
        partial void OnDoorsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Color
        {
            get
            {
                return _Color;
            }
            set
            {
                OnColorChanging(value);
                ReportPropertyChanging("Color");
                _Color = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Color");
                OnColorChanged();
            }
        }
        private global::System.String _Color;
        partial void OnColorChanging(global::System.String value);
        partial void OnColorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Salvage
        {
            get
            {
                return _Salvage;
            }
            set
            {
                OnSalvageChanging(value);
                ReportPropertyChanging("Salvage");
                _Salvage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Salvage");
                OnSalvageChanged();
            }
        }
        private global::System.Boolean _Salvage;
        partial void OnSalvageChanging(global::System.Boolean value);
        partial void OnSalvageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TitleStatus
        {
            get
            {
                return _TitleStatus;
            }
            set
            {
                OnTitleStatusChanging(value);
                ReportPropertyChanging("TitleStatus");
                _TitleStatus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TitleStatus");
                OnTitleStatusChanged();
            }
        }
        private global::System.String _TitleStatus;
        partial void OnTitleStatusChanging(global::System.String value);
        partial void OnTitleStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DriveTrain
        {
            get
            {
                return _DriveTrain;
            }
            set
            {
                OnDriveTrainChanging(value);
                ReportPropertyChanging("DriveTrain");
                _DriveTrain = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DriveTrain");
                OnDriveTrainChanged();
            }
        }
        private global::System.String _DriveTrain;
        partial void OnDriveTrainChanging(global::System.String value);
        partial void OnDriveTrainChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InteriorType
        {
            get
            {
                return _InteriorType;
            }
            set
            {
                OnInteriorTypeChanging(value);
                ReportPropertyChanging("InteriorType");
                _InteriorType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InteriorType");
                OnInteriorTypeChanged();
            }
        }
        private global::System.String _InteriorType;
        partial void OnInteriorTypeChanging(global::System.String value);
        partial void OnInteriorTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TopType
        {
            get
            {
                return _TopType;
            }
            set
            {
                OnTopTypeChanging(value);
                ReportPropertyChanging("TopType");
                _TopType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TopType");
                OnTopTypeChanged();
            }
        }
        private global::System.String _TopType;
        partial void OnTopTypeChanging(global::System.String value);
        partial void OnTopTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Stereo
        {
            get
            {
                return _Stereo;
            }
            set
            {
                OnStereoChanging(value);
                ReportPropertyChanging("Stereo");
                _Stereo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Stereo");
                OnStereoChanged();
            }
        }
        private global::System.String _Stereo;
        partial void OnStereoChanging(global::System.String value);
        partial void OnStereoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Airbags
        {
            get
            {
                return _Airbags;
            }
            set
            {
                OnAirbagsChanging(value);
                ReportPropertyChanging("Airbags");
                _Airbags = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Airbags");
                OnAirbagsChanged();
            }
        }
        private global::System.String _Airbags;
        partial void OnAirbagsChanging(global::System.String value);
        partial void OnAirbagsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Options
        {
            get
            {
                return _Options;
            }
            set
            {
                OnOptionsChanging(value);
                ReportPropertyChanging("Options");
                _Options = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Options");
                OnOptionsChanged();
            }
        }
        private global::System.String _Options;
        partial void OnOptionsChanging(global::System.String value);
        partial void OnOptionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StatusId
        {
            get
            {
                return _StatusId;
            }
            set
            {
                OnStatusIdChanging(value);
                ReportPropertyChanging("StatusId");
                _StatusId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StatusId");
                OnStatusIdChanged();
            }
        }
        private global::System.Int32 _StatusId;
        partial void OnStatusIdChanging(global::System.Int32 value);
        partial void OnStatusIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Odometer
        {
            get
            {
                return _Odometer;
            }
            set
            {
                OnOdometerChanging(value);
                ReportPropertyChanging("Odometer");
                _Odometer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Odometer");
                OnOdometerChanged();
            }
        }
        private Nullable<global::System.Int32> _Odometer;
        partial void OnOdometerChanging(Nullable<global::System.Int32> value);
        partial void OnOdometerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InServiceDate
        {
            get
            {
                return _InServiceDate;
            }
            set
            {
                OnInServiceDateChanging(value);
                ReportPropertyChanging("InServiceDate");
                _InServiceDate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InServiceDate");
                OnInServiceDateChanged();
            }
        }
        private global::System.String _InServiceDate;
        partial void OnInServiceDateChanging(global::System.String value);
        partial void OnInServiceDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TitleState
        {
            get
            {
                return _TitleState;
            }
            set
            {
                OnTitleStateChanging(value);
                ReportPropertyChanging("TitleState");
                _TitleState = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TitleState");
                OnTitleStateChanged();
            }
        }
        private global::System.String _TitleState;
        partial void OnTitleStateChanging(global::System.String value);
        partial void OnTitleStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FuelType
        {
            get
            {
                return _FuelType;
            }
            set
            {
                OnFuelTypeChanging(value);
                ReportPropertyChanging("FuelType");
                _FuelType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FuelType");
                OnFuelTypeChanged();
            }
        }
        private global::System.String _FuelType;
        partial void OnFuelTypeChanging(global::System.String value);
        partial void OnFuelTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Engine
        {
            get
            {
                return _Engine;
            }
            set
            {
                OnEngineChanging(value);
                ReportPropertyChanging("Engine");
                _Engine = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Engine");
                OnEngineChanged();
            }
        }
        private global::System.String _Engine;
        partial void OnEngineChanging(global::System.String value);
        partial void OnEngineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Displacement
        {
            get
            {
                return _Displacement;
            }
            set
            {
                OnDisplacementChanging(value);
                ReportPropertyChanging("Displacement");
                _Displacement = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Displacement");
                OnDisplacementChanged();
            }
        }
        private global::System.String _Displacement;
        partial void OnDisplacementChanging(global::System.String value);
        partial void OnDisplacementChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Transmission
        {
            get
            {
                return _Transmission;
            }
            set
            {
                OnTransmissionChanging(value);
                ReportPropertyChanging("Transmission");
                _Transmission = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Transmission");
                OnTransmissionChanged();
            }
        }
        private global::System.String _Transmission;
        partial void OnTransmissionChanging(global::System.String value);
        partial void OnTransmissionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExteriorColor
        {
            get
            {
                return _ExteriorColor;
            }
            set
            {
                OnExteriorColorChanging(value);
                ReportPropertyChanging("ExteriorColor");
                _ExteriorColor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExteriorColor");
                OnExteriorColorChanged();
            }
        }
        private global::System.String _ExteriorColor;
        partial void OnExteriorColorChanging(global::System.String value);
        partial void OnExteriorColorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InteriorColor
        {
            get
            {
                return _InteriorColor;
            }
            set
            {
                OnInteriorColorChanging(value);
                ReportPropertyChanging("InteriorColor");
                _InteriorColor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InteriorColor");
                OnInteriorColorChanged();
            }
        }
        private global::System.String _InteriorColor;
        partial void OnInteriorColorChanging(global::System.String value);
        partial void OnInteriorColorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WindowSticker
        {
            get
            {
                return _WindowSticker;
            }
            set
            {
                OnWindowStickerChanging(value);
                ReportPropertyChanging("WindowSticker");
                _WindowSticker = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WindowSticker");
                OnWindowStickerChanged();
            }
        }
        private global::System.String _WindowSticker;
        partial void OnWindowStickerChanging(global::System.String value);
        partial void OnWindowStickerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Cylinders
        {
            get
            {
                return _Cylinders;
            }
            set
            {
                OnCylindersChanging(value);
                ReportPropertyChanging("Cylinders");
                _Cylinders = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cylinders");
                OnCylindersChanged();
            }
        }
        private Nullable<global::System.Int32> _Cylinders;
        partial void OnCylindersChanging(Nullable<global::System.Int32> value);
        partial void OnCylindersChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MMR
        {
            get
            {
                return _MMR;
            }
            set
            {
                OnMMRChanging(value);
                ReportPropertyChanging("MMR");
                _MMR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MMR");
                OnMMRChanged();
            }
        }
        private Nullable<global::System.Int32> _MMR;
        partial void OnMMRChanging(Nullable<global::System.Int32> value);
        partial void OnMMRChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ManheimModel", "FK_PreSale_Vehicle", "PreSale")]
        public EntityCollection<PreSale> PreSales
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PreSale>("ManheimModel.FK_PreSale_Vehicle", "PreSale");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PreSale>("ManheimModel.FK_PreSale_Vehicle", "PreSale", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ManheimModel", "FK_Vehicle_VehicleStatus", "VehicleStatu")]
        public VehicleStatus VehicleStatus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VehicleStatus>("ManheimModel.FK_Vehicle_VehicleStatus", "VehicleStatu").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VehicleStatus>("ManheimModel.FK_Vehicle_VehicleStatus", "VehicleStatu").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<VehicleStatus> VehicleStatusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VehicleStatus>("ManheimModel.FK_Vehicle_VehicleStatus", "VehicleStatu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<VehicleStatus>("ManheimModel.FK_Vehicle_VehicleStatus", "VehicleStatu", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ManheimModel", Name="VehicleStatus")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VehicleStatus : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VehicleStatus object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static VehicleStatus CreateVehicleStatus(global::System.Int32 id, global::System.String name)
        {
            VehicleStatus vehicleStatus = new VehicleStatus();
            vehicleStatus.Id = id;
            vehicleStatus.Name = name;
            return vehicleStatus;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
    }

    #endregion
    
}
