//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace Manheim.Model
{
    public partial class ManheimEntities : ObjectContext
    {
        public const string ConnectionString = "name=ManheimEntities";
        public const string ContainerName = "ManheimEntities";
    
        #region Constructors
    
        public ManheimEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        public ManheimEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        public ManheimEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Auction> Auctions
        {
            get { return _auctions  ?? (_auctions = CreateObjectSet<Auction>("Auctions")); }
        }
        private ObjectSet<Auction> _auctions;
    
        public ObjectSet<Manager> Managers
        {
            get { return _managers  ?? (_managers = CreateObjectSet<Manager>("Managers")); }
        }
        private ObjectSet<Manager> _managers;
    
        public ObjectSet<State> States
        {
            get { return _states  ?? (_states = CreateObjectSet<State>("States")); }
        }
        private ObjectSet<State> _states;
    
        public ObjectSet<PreSale> PreSales
        {
            get { return _preSales  ?? (_preSales = CreateObjectSet<PreSale>("PreSales")); }
        }
        private ObjectSet<PreSale> _preSales;
    
        public ObjectSet<Vehicle> Vehicles
        {
            get { return _vehicles  ?? (_vehicles = CreateObjectSet<Vehicle>("Vehicles")); }
        }
        private ObjectSet<Vehicle> _vehicles;
    
        public ObjectSet<VehicleStatus> VehicleStatuses
        {
            get { return _vehicleStatuses  ?? (_vehicleStatuses = CreateObjectSet<VehicleStatus>("VehicleStatuses")); }
        }
        private ObjectSet<VehicleStatus> _vehicleStatuses;
    
        public ObjectSet<Seller> Sellers
        {
            get { return _sellers  ?? (_sellers = CreateObjectSet<Seller>("Sellers")); }
        }
        private ObjectSet<Seller> _sellers;

        #endregion
    }
}
