//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manheim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller
    {
        public Seller()
        {
            this.PreSales = new HashSet<PreSale>();
        }
    
        public int SellerId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<PreSale> PreSales { get; set; }
    }
}
