//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manheim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public Vehicle()
        {
            this.PreSales = new HashSet<PreSale>();
        }
    
        public string VIN { get; set; }
        public int Year { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string BodyStyle { get; set; }
        public string TrimLevel { get; set; }
        public string VehicleType { get; set; }
        public Nullable<int> Doors { get; set; }
        public string Color { get; set; }
        public bool Salvage { get; set; }
        public string TitleStatus { get; set; }
        public string DriveTrain { get; set; }
        public string InteriorType { get; set; }
        public string TopType { get; set; }
        public string Stereo { get; set; }
        public string Airbags { get; set; }
        public string Options { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> Odometer { get; set; }
        public string InServiceDate { get; set; }
        public string TitleState { get; set; }
        public string FuelType { get; set; }
        public string Engine { get; set; }
        public string Displacement { get; set; }
        public string Transmission { get; set; }
        public string ExteriorColor { get; set; }
        public string InteriorColor { get; set; }
        public string WindowSticker { get; set; }
        public Nullable<int> Cylinders { get; set; }
        public Nullable<int> MMR { get; set; }
        public Nullable<double> Grade { get; set; }
    
        public virtual ICollection<PreSale> PreSales { get; set; }
        public virtual VehicleStatus VehicleStatus { get; set; }
    }
}
