//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace TimeCard.MVC.Models
{
    public partial class vRateCodeType
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Priority { get; set; }
        public string Rule { get; set; }
        public int RuleId { get; set; }
        public int IsRuleOver { get; set; }
        public int IsRuleExtra { get; set; }
        public int RulePriority { get; set; }
    }
    
}
