//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace TimeCard.MVC.Models
{
    public partial class vWorkDayRate
    {
        public System.DateTime Date { get; set; }
        public int HourFrom { get; set; }
        public int HourTill { get; set; }
        public int RateMinutes { get; set; }
        public string RateCode { get; set; }
        public int RateCodeId { get; set; }
        public double Rate { get; set; }
    }
    
}
