//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace TimeCard.MVC.Models
{
    public partial class vWorkShiftMinuteWithRate
    {
        public System.DateTimeOffset WorkShiftStart { get; set; }
        public int RateCodeId { get; set; }
        public Nullable<int> Minutes { get; set; }
        public Nullable<int> Hours { get; set; }
    }
    
}
